#Config file for testing Katago

#Path to find puzzles in
puzzlespath: "/Users/blake/Research/Puzzle-Engine/puzzle_files/"

#Board size used
boardsize: 7

#Command used to start engine -- passed to Popen()
command:
  - "katago"
  - "gtp"
  - "-model"
  - "/opt/homebrew/Cellar/katago/1.13.2/share/katago/g170e-b20c256x2-s5303129600-d1228401921.bin.gz"
  - "-config"
  - "gtp_example.cfg"

cwdpath: "/opt/homebrew/Cellar/katago/1.13.2/share/katago/configs"
