#Config file used for non-engine-specific attributes

#List name of engine to test
engines:
  - "katago"
  - "leela"
  - "test"
  - "model_n"
  - "model_o"

#Engines Folder
engines_path: "/Users/blake/Research/Puzzle-Go/external_engines/"

#Folder storing tests (sgf files)
puzzles_path: "/Users/blake/Research/Puzzle-Go/puzzle_files/"

#Folder to log datapoints from engines solving puzzles
puzzle_logs_path: "/Users/blake/Research/Puzzle-Go/puzzle_logs"

#Board size used for testing 
boardsize: 7

#Set to true if you want to run all tests
runalltests: true

#Test Puzzle Rotations
rotate_puzzles: true

#Only need to fill in if you want to list specific puzzles to run
run_tests:
  - "None"

#Number of tests to run per puzzle
tests_per_puzzle: 1
